--liquibase formatted sql

--changeset arkana:20260817-06-seed-marseille-deck
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(*) from public.decks where id = 'marseille'
insert into public.decks (
  id, display_order, name_pt_br, name_en, card_count, active
) values (
  'marseille', 2, 'Tarot de Marselha', 'Tarot de Marseille', 78, true
);

--changeset arkana:20260817-07-seed-marseille-major-arcana
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(*) from public.tarot_cards where deck_id = 'marseille' and suit = 'major'
insert into public.tarot_cards (
  id, deck_id, card_number, suit, image_path,
  name_pt_br, name_en, description_pt_br, description_en,
  light_pt_br, light_en, shadow_pt_br, shadow_en
)
values
  ('marseille-le-mat', 'marseille', 0, 'major', '00-LeMat.png',
   'O Louco', 'The Fool',
   'O Louco avança fora da ordem numerada, levando apenas o necessário. No Marselha, seu passo errante fala de liberdade, impulso e abertura ao que ainda não tem forma.',
   'The Fool travels outside the numbered order, carrying only what is needed. In Marseille imagery, his wandering step speaks of freedom, impulse, and openness to what has not yet taken shape.',
   'Disponibilidade para começar, experimentar e seguir um chamado autêntico sem exigir garantias prematuras.',
   'Readiness to begin, experiment, and follow an authentic calling without demanding premature guarantees.',
   'Dispersão, imprudência ou fuga de compromissos. O movimento perde sentido quando não reconhece consequências.',
   'Restlessness, recklessness, or escape from commitment. Movement loses meaning when consequences are ignored.'),
  ('marseille-le-bateleur', 'marseille', 1, 'major', '01-LeBateleur.png',
   'O Mago', 'The Magician',
   'Diante de sua mesa, O Mago reúne ferramentas e possibilidades. Ele inaugura a sequência com habilidade, curiosidade e poder de transformar intenção em gesto.',
   'At his table, The Magician gathers tools and possibilities. He opens the sequence with skill, curiosity, and the power to turn intention into action.',
   'Iniciativa, destreza e uso criativo dos recursos que já estão ao alcance.',
   'Initiative, dexterity, and creative use of the resources already at hand.',
   'Improviso vazio, manipulação ou talento usado sem direção e responsabilidade.',
   'Empty improvisation, manipulation, or talent used without direction and responsibility.'),
  ('marseille-la-papesse', 'marseille', 2, 'major', '02-LaPapesse.png',
   'A Papisa', 'The Popess',
   'A Papisa guarda um livro e um conhecimento que não se oferece de imediato. Sua presença pede silêncio, observação e maturação interior.',
   'The Popess guards a book and knowledge that is not immediately revealed. Her presence calls for silence, observation, and inner ripening.',
   'Intuição, estudo paciente e capacidade de perceber o que existe por trás das aparências.',
   'Intuition, patient study, and the ability to perceive what lies behind appearances.',
   'Passividade, segredo defensivo ou espera que substitui uma ação necessária.',
   'Passivity, defensive secrecy, or waiting that replaces a necessary action.'),
  ('marseille-l-imperatrice', 'marseille', 3, 'major', '03-LImperatrice.png',
   'A Imperatriz', 'The Empress',
   'A Imperatriz une inteligência, expressão e força criadora. O cetro e o escudo mostram uma ideia pronta para ganhar linguagem e presença no mundo.',
   'The Empress joins intelligence, expression, and creative force. Her scepter and shield show an idea ready to gain language and presence in the world.',
   'Criatividade fértil, comunicação viva e confiança para desenvolver uma visão.',
   'Fertile creativity, lively communication, and confidence to develop a vision.',
   'Vaidade, excesso de ideias ou sedução usada para evitar profundidade e continuidade.',
   'Vanity, an excess of ideas, or charm used to avoid depth and continuity.'),
  ('marseille-l-empereur', 'marseille', 4, 'major', '04-LEmpereur.png',
   'O Imperador', 'The Emperor',
   'O Imperador sustenta a matéria e delimita um território. Sua estabilidade transforma intenção em estrutura, regra e continuidade.',
   'The Emperor sustains the material world and defines a territory. His stability turns intention into structure, rules, and continuity.',
   'Organização, autoridade responsável e construção de bases capazes de durar.',
   'Organization, responsible authority, and the building of foundations that can last.',
   'Rigidez, controle excessivo ou apego a uma posição que já não serve ao conjunto.',
   'Rigidity, excessive control, or attachment to a position that no longer serves the whole.'),
  ('marseille-le-pape', 'marseille', 5, 'major', '05-LePape.png',
   'O Papa', 'The Pope',
   'O Papa transmite uma bênção e liga experiência a ensinamento. Ele representa tradição viva, orientação e responsabilidade ética na partilha do saber.',
   'The Pope offers a blessing and connects experience with teaching. He represents living tradition, guidance, and ethical responsibility in sharing knowledge.',
   'Conselho confiável, aprendizagem e compromisso com valores que dão sentido à ação.',
   'Trustworthy counsel, learning, and commitment to values that give action meaning.',
   'Dogmatismo, dependência de aprovação ou uso da autoridade para silenciar diferenças.',
   'Dogmatism, dependence on approval, or the use of authority to silence differences.'),
  ('marseille-l-amoureux', 'marseille', 6, 'major', '06-LAmoureux.png',
   'Os Enamorados', 'The Lovers',
   'Os Enamorados colocam o desejo diante de uma escolha. Vínculos, valores e vozes diferentes precisam encontrar uma decisão assumida.',
   'The Lovers place desire before a choice. Bonds, values, and different voices must find a decision that can be owned.',
   'Encontro, reciprocidade e escolha alinhada ao que o coração reconhece como verdadeiro.',
   'Connection, reciprocity, and a choice aligned with what the heart recognizes as true.',
   'Indecisão, triangulação ou busca de prazer sem aceitar as consequências da escolha.',
   'Indecision, triangulation, or pursuit of pleasure without accepting the consequences of choice.'),
  ('marseille-le-chariot', 'marseille', 7, 'major', '07-LeChariot.png',
   'O Carro', 'The Chariot',
   'O Carro reúne forças distintas numa mesma direção. A vitória sugerida pela carta depende de condução, presença e domínio do próprio impulso.',
   'The Chariot gathers different forces into one direction. The victory suggested by the card depends on guidance, presence, and mastery of one’s own drive.',
   'Avanço, autonomia e determinação para ocupar um novo lugar com confiança.',
   'Progress, autonomy, and determination to take a new place with confidence.',
   'Pressa, arrogância ou movimento exterior que tenta esconder conflitos ainda não integrados.',
   'Haste, arrogance, or outward movement used to hide conflicts that remain unresolved.'),
  ('marseille-la-justice', 'marseille', 8, 'major', '08-LaJustice.png',
   'A Justiça', 'Justice',
   'A Justiça, arcano VIII no Marselha, equilibra a balança e ergue a espada. Ela pede medida, consequência e uma decisão que possa ser sustentada pelos fatos.',
   'Justice, trump VIII in the Marseille order, balances the scales and raises the sword. She calls for measure, consequence, and a decision that can be supported by facts.',
   'Clareza, equidade e responsabilidade por escolhas, acordos e limites.',
   'Clarity, fairness, and responsibility for choices, agreements, and boundaries.',
   'Julgamento rígido, racionalização ou tentativa de exigir do outro o equilíbrio que falta em si.',
   'Harsh judgment, rationalization, or demanding from others the balance missing within oneself.'),
  ('marseille-l-ermite', 'marseille', 9, 'major', '09-LHermite.png',
   'O Eremita', 'The Hermit',
   'O Eremita protege a chama e avança devagar. Seu tempo é o da experiência que examina, depura e ilumina apenas o próximo passo.',
   'The Hermit shelters the flame and moves slowly. His time is that of experience that examines, refines, and illuminates only the next step.',
   'Prudência, pesquisa interior e sabedoria adquirida pela observação paciente.',
   'Prudence, inner inquiry, and wisdom gained through patient observation.',
   'Isolamento, medo de participar ou análise prolongada que evita o retorno ao mundo.',
   'Isolation, fear of participation, or prolonged analysis that avoids returning to the world.'),
  ('marseille-la-roue-de-fortune', 'marseille', 10, 'major', '10-LaRoueDeFortune.png',
   'A Roda da Fortuna', 'Wheel of Fortune',
   'A Roda da Fortuna mostra posições que sobem, descem e se alternam. Ela recorda que ciclos mudam e que a resposta está na forma de participar do movimento.',
   'The Wheel of Fortune shows positions rising, falling, and changing places. It reminds us that cycles turn and that the answer lies in how we participate in movement.',
   'Virada, oportunidade e flexibilidade para responder a uma nova condição.',
   'A turning point, opportunity, and flexibility in responding to new conditions.',
   'Repetição automática, instabilidade ou tentativa de controlar aquilo que é cíclico.',
   'Automatic repetition, instability, or an attempt to control what is cyclical.'),
  ('marseille-la-force', 'marseille', 11, 'major', '11-LaForce.png',
   'A Força', 'Strength',
   'A Força, arcano XI no Marselha, abre a boca do leão sem violência. A imagem fala de potência conduzida por consciência, firmeza e intimidade com o instinto.',
   'Strength, trump XI in the Marseille order, opens the lion’s mouth without violence. The image speaks of power guided by awareness, steadiness, and intimacy with instinct.',
   'Coragem serena, vitalidade e capacidade de orientar impulsos sem reprimi-los.',
   'Calm courage, vitality, and the ability to guide impulses without repressing them.',
   'Dominação, explosão emocional ou esforço contínuo para parecer mais forte do que se sente.',
   'Domination, emotional eruption, or constant effort to appear stronger than one feels.'),
  ('marseille-le-pendu', 'marseille', 12, 'major', '12-LePendu.png',
   'O Enforcado', 'The Hanged Man',
   'Suspenso por um pé, O Enforcado troca ação por uma visão invertida. A pausa pode revelar o que a pressa e os hábitos mantinham oculto.',
   'Suspended by one foot, The Hanged Man exchanges action for an inverted view. The pause can reveal what haste and habit kept hidden.',
   'Entrega consciente, mudança de perspectiva e disponibilidade para soltar uma expectativa.',
   'Conscious surrender, a shift in perspective, and willingness to release an expectation.',
   'Estagnação, sacrifício ressentido ou espera usada para adiar uma escolha possível.',
   'Stagnation, resentful sacrifice, or waiting used to postpone a possible choice.'),
  ('marseille-arcano-sem-nome', 'marseille', 13, 'major', '13-ArcaneSansNom.png',
   'Arcano sem Nome', 'The Nameless Arcanum',
   'Tradicionalmente sem nome impresso, o arcano XIII ceifa formas já esgotadas. Sua ação não é punição, mas limpeza radical para que a vida volte a circular.',
   'Traditionally printed without a name, trump XIII cuts down exhausted forms. Its action is not punishment but radical clearing so that life may circulate again.',
   'Encerramento necessário, transformação profunda e libertação do que perdeu vitalidade.',
   'Necessary ending, deep transformation, and release of what has lost vitality.',
   'Apego, medo da perda ou destruição indiscriminada que confunde mudança com ruptura total.',
   'Attachment, fear of loss, or indiscriminate destruction that confuses change with total rupture.'),
  ('marseille-temperance', 'marseille', 14, 'major', '14-Temperance.png',
   'A Temperança', 'Temperance',
   'A Temperança faz circular o conteúdo entre dois vasos. Ela combina diferenças, regula excessos e encontra um ritmo no qual a transformação pode ser assimilada.',
   'Temperance circulates liquid between two vessels. She combines differences, regulates excess, and finds a rhythm in which transformation can be absorbed.',
   'Conciliação, cura gradual e adaptação paciente entre necessidades distintas.',
   'Reconciliation, gradual healing, and patient adaptation between different needs.',
   'Diluição, acomodação excessiva ou dificuldade de reconhecer que algo chegou ao limite.',
   'Dilution, excessive accommodation, or difficulty recognizing that something has reached its limit.'),
  ('marseille-le-diable', 'marseille', 15, 'major', '15-LeDiable.png',
   'O Diabo', 'The Devil',
   'O Diabo reúne desejo, matéria e poder instintivo. As figuras ligadas ao pedestal mostram vínculos cuja força aumenta quando permanecem inconscientes.',
   'The Devil brings together desire, matter, and instinctive power. The figures bound to the pedestal show bonds whose strength grows when they remain unconscious.',
   'Vitalidade, magnetismo e coragem para reconhecer desejos, dependências e poder pessoal.',
   'Vitality, magnetism, and courage to recognize desire, dependency, and personal power.',
   'Compulsão, manipulação ou acordo que oferece prazer ao custo de autonomia.',
   'Compulsion, manipulation, or an agreement that offers pleasure at the cost of autonomy.'),
  ('marseille-la-maison-dieu', 'marseille', 16, 'major', '16-LaMaisonDieu.png',
   'A Casa de Deus', 'The House of God',
   'A Casa de Deus abre sua coroa e libera o que estava fechado. A ruptura desmonta uma construção rígida, mas também devolve energia, verdade e movimento.',
   'The House of God opens its crown and releases what was enclosed. The rupture dismantles a rigid construction while returning energy, truth, and movement.',
   'Revelação, libertação e queda de uma estrutura que já impedia o crescimento.',
   'Revelation, liberation, and the fall of a structure that had begun to prevent growth.',
   'Crise amplificada, orgulho ferido ou insistência em reconstruir exatamente a mesma prisão.',
   'An escalating crisis, wounded pride, or insistence on rebuilding the very same prison.'),
  ('marseille-l-etoile', 'marseille', 17, 'major', '17-LEtoile.png',
   'A Estrela', 'The Star',
   'Sob as estrelas, uma figura oferece água à terra e ao fluxo. A carta fala de confiança simples, pertencimento e generosidade que renova o ambiente.',
   'Beneath the stars, a figure offers water to earth and stream. The card speaks of simple trust, belonging, and generosity that renews the surroundings.',
   'Esperança lúcida, inspiração e expressão autêntica sem necessidade de defesa.',
   'Clear-eyed hope, inspiration, and authentic expression without the need for defense.',
   'Exposição sem limites, ingenuidade ou expectativa de que a inspiração substitua o cuidado concreto.',
   'Exposure without boundaries, naivety, or expecting inspiration to replace practical care.'),
  ('marseille-la-lune', 'marseille', 18, 'major', '18-LaLune.png',
   'A Lua', 'The Moon',
   'A Lua governa marés, reflexos e percepções noturnas. Entre torres, animais e água profunda, ela aproxima memória, imaginação e incerteza.',
   'The Moon governs tides, reflections, and nocturnal perception. Between towers, animals, and deep water, she brings memory, imagination, and uncertainty close together.',
   'Sensibilidade, sonho e escuta das mensagens que surgem por imagens e emoções.',
   'Sensitivity, dreaming, and attention to messages arriving through image and emotion.',
   'Confusão, projeção ou medo alimentado por sinais que ainda não foram verificados.',
   'Confusion, projection, or fear fed by signs that have not yet been verified.'),
  ('marseille-le-soleil', 'marseille', 19, 'major', '19-LeSoleil.png',
   'O Sol', 'The Sun',
   'O Sol ilumina duas figuras que se encontram diante de um muro. Calor, clareza e cooperação tornam visível aquilo que pode crescer em comum.',
   'The Sun illuminates two figures meeting before a wall. Warmth, clarity, and cooperation reveal what can grow in common.',
   'Alegria, vitalidade, reconhecimento e relações fortalecidas por transparência.',
   'Joy, vitality, recognition, and relationships strengthened by transparency.',
   'Egocentrismo, excesso de exposição ou certeza que não deixa espaço para a experiência do outro.',
   'Egocentrism, overexposure, or certainty that leaves no room for another person’s experience.'),
  ('marseille-le-jugement', 'marseille', 20, 'major', '20-LeJugement.png',
   'O Julgamento', 'Judgement',
   'Ao chamado do anjo, algo se levanta e responde. O Julgamento reúne memória e despertar, anunciando uma compreensão que muda a forma de participar da própria história.',
   'At the angel’s call, something rises and answers. Judgement joins memory with awakening, announcing an understanding that changes how one participates in one’s own story.',
   'Renascimento, chamado claro e reconciliação com uma verdade que pede expressão.',
   'Renewal, a clear calling, and reconciliation with a truth that asks to be expressed.',
   'Culpa, medo de avaliação ou tentativa de reviver o passado sem transformá-lo.',
   'Guilt, fear of evaluation, or an attempt to revive the past without transforming it.'),
  ('marseille-le-monde', 'marseille', 21, 'major', '21-LeMonde.png',
   'O Mundo', 'The World',
   'No centro da mandorla, O Mundo integra os quatro cantos da experiência. A sequência encontra plenitude, circulação e uma forma completa que pode novamente se abrir.',
   'At the center of the mandorla, The World integrates the four corners of experience. The sequence finds fullness, circulation, and a complete form ready to open again.',
   'Realização, integração e participação madura num todo maior.',
   'Fulfillment, integration, and mature participation in a greater whole.',
   'Dificuldade de concluir, perfeccionismo ou isolamento depois de alcançar uma posição desejada.',
   'Difficulty completing, perfectionism, or isolation after reaching a desired position.');

--changeset arkana:20260817-08-seed-marseille-minor-arcana
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(*) from public.tarot_cards where deck_id = 'marseille' and suit <> 'major'
insert into public.tarot_cards (
  id, deck_id, card_number, suit, image_path,
  name_pt_br, name_en, description_pt_br, description_en,
  light_pt_br, light_en, shadow_pt_br, shadow_en
)
with suits (
  suit, file_prefix, name_pt_br, name_en,
  domain_pt_br, domain_en, light_pt_br, light_en, shadow_pt_br, shadow_en
) as (values
  ('cups', 'Coupes', 'Copas', 'Cups',
   'afetos, vínculos, imaginação e receptividade', 'feeling, relationships, imagination, and receptivity',
   'A escuta emocional favorece vínculo e circulação afetiva.', 'Emotional attention supports connection and the circulation of feeling.',
   'Carência, idealização ou emoção represada podem distorcer a troca.', 'Neediness, idealization, or blocked emotion may distort the exchange.'),
  ('pentacles', 'Deniers', 'Ouros', 'Coins',
   'corpo, recursos, trabalho e sustentação material', 'the body, resources, work, and material support',
   'Presença prática ajuda a tornar valor, cuidado e recursos mais consistentes.', 'Practical presence helps value, care, and resources become more consistent.',
   'Apego, escassez percebida ou excesso de cálculo podem imobilizar a matéria.', 'Attachment, perceived scarcity, or overcalculation may immobilize material life.'),
  ('swords', 'Epees', 'Espadas', 'Swords',
   'pensamento, decisão, conflito e discernimento', 'thought, decision, conflict, and discernment',
   'Clareza e precisão permitem separar fatos, ideias e escolhas.', 'Clarity and precision help distinguish facts, ideas, and choices.',
   'Rigidez mental, hostilidade ou análise sem escuta podem aprofundar a divisão.', 'Mental rigidity, hostility, or analysis without listening may deepen division.'),
  ('wands', 'Batons', 'Paus', 'Batons',
   'desejo, criatividade, trabalho vivo e impulso de realização', 'desire, creativity, living effort, and the drive to accomplish',
   'Iniciativa e presença colocam a energia criadora em movimento.', 'Initiative and presence set creative energy in motion.',
   'Impulsividade, disputa ou desgaste podem dispersar a força disponível.', 'Impulsiveness, rivalry, or exhaustion may scatter the available force.')
), ranks (
  card_number, id_rank, file_number, name_pt_br, name_en,
  visual_pt_br, visual_en, stage_pt_br, stage_en,
  light_pt_br, light_en, shadow_pt_br, shadow_en
) as (values
  (1, 'ace', 1, 'Ás', 'Ace',
   'um único emblema concentra a potência do naipe', 'a single emblem concentrates the suit’s potential',
   'o princípio, a semente e a energia ainda indivisa', 'a beginning, seed, and energy not yet divided',
   'Uma possibilidade essencial pode ser reconhecida e iniciada.', 'An essential possibility can be recognized and begun.',
   'Potencial sem direção ou início adiado mantém a energia apenas como promessa.', 'Potential without direction, or a delayed beginning, keeps energy only as a promise.'),
  (2, 'two', 2, 'Dois', 'Two',
   'dois emblemas criam espelho, tensão e reciprocidade', 'two emblems create mirroring, tension, and reciprocity',
   'a polaridade, o encontro e a necessidade de relação', 'polarity, encounter, and the need for relationship',
   'Duas forças podem dialogar e encontrar uma medida comum.', 'Two forces can enter dialogue and find a shared measure.',
   'Dualidade rígida ou hesitação prolongada impede composição.', 'Rigid duality or prolonged hesitation prevents composition.'),
  (3, 'three', 3, 'Três', 'Three',
   'três emblemas inauguram ritmo e desenvolvimento', 'three emblems introduce rhythm and development',
   'a criação que nasce do encontro entre duas forças', 'creation born from the meeting of two forces',
   'Expressão, crescimento e colaboração dão corpo ao que começou.', 'Expression, growth, and collaboration give form to what has begun.',
   'Expansão sem centro ou interferência de uma terceira força pode dispersar o propósito.', 'Expansion without a center, or interference from a third force, may scatter purpose.'),
  (4, 'four', 4, 'Quatro', 'Four',
   'quatro emblemas estabelecem uma forma estável', 'four emblems establish a stable form',
   'a estrutura, a base e a conservação do que foi construído', 'structure, foundation, and preservation of what has been built',
   'Limites claros oferecem segurança para sustentar o processo.', 'Clear boundaries provide security for sustaining the process.',
   'Estabilidade pode endurecer em controle, repetição ou fechamento.', 'Stability may harden into control, repetition, or closure.'),
  (5, 'five', 5, 'Cinco', 'Five',
   'um quinto emblema rompe a simetria e exige reorganização', 'a fifth emblem breaks symmetry and demands reorganization',
   'a crise, a passagem e o elemento que desafia a ordem existente', 'crisis, transition, and the element that challenges the existing order',
   'O desconforto revela onde mudança e adaptação são necessárias.', 'Discomfort reveals where change and adaptation are needed.',
   'Conflito sem elaboração pode virar perda, ressentimento ou caos repetido.', 'Unprocessed conflict may become loss, resentment, or repeated chaos.'),
  (6, 'six', 6, 'Seis', 'Six',
   'seis emblemas recuperam equilíbrio em uma composição mais ampla', 'six emblems restore balance in a broader composition',
   'a conciliação, a beleza e a circulação depois da crise', 'reconciliation, beauty, and renewed circulation after crisis',
   'Ajustes conscientes restauram harmonia e capacidade de troca.', 'Conscious adjustments restore harmony and the capacity to exchange.',
   'Busca de harmonia aparente pode ocultar dependência ou conflito não resolvido.', 'The pursuit of surface harmony may hide dependency or unresolved conflict.'),
  (7, 'seven', 7, 'Sete', 'Seven',
   'sete emblemas tornam a ordem mais complexa e móvel', 'seven emblems make the order more complex and mobile',
   'a prova, a estratégia e o avanço que requer consciência', 'testing, strategy, and progress that requires awareness',
   'Discernimento e estratégia permitem atravessar uma etapa exigente.', 'Discernment and strategy make it possible to cross a demanding stage.',
   'Defensividade, fantasia ou cálculo excessivo confundem a direção.', 'Defensiveness, fantasy, or excessive calculation confuse direction.'),
  (8, 'eight', 8, 'Oito', 'Eight',
   'oito emblemas formam uma trama concentrada e operativa', 'eight emblems form a concentrated and operative pattern',
   'a organização, o domínio técnico e a transformação pelo exercício', 'organization, technical mastery, and transformation through practice',
   'Repetição consciente e habilidade colocam o processo em pleno funcionamento.', 'Conscious repetition and skill bring the process into full operation.',
   'Automatismo, perfeccionismo ou excesso de atividade aprisionam a energia.', 'Automatic behavior, perfectionism, or excessive activity trap the energy.'),
  (9, 'nine', 9, 'Nove', 'Nine',
   'nove emblemas mostram uma forma madura próxima de seu limite', 'nine emblems show a mature form approaching its limit',
   'a autonomia, a experiência acumulada e a preparação para concluir', 'autonomy, accumulated experience, and preparation to conclude',
   'Maturidade e autonomia permitem reconhecer o valor já alcançado.', 'Maturity and autonomy make it possible to recognize value already achieved.',
   'Isolamento, ansiedade ou apego à quase conclusão impedem descanso e partilha.', 'Isolation, anxiety, or attachment to near-completion prevent rest and sharing.'),
  (10, 'ten', 10, 'Dez', 'Ten',
   'dez emblemas completam e saturam a arquitetura do naipe', 'ten emblems complete and saturate the suit’s architecture',
   'a culminação, o resultado e a passagem para um novo ciclo', 'culmination, result, and passage into a new cycle',
   'O ciclo pode ser integrado, compartilhado e transformado em experiência.', 'The cycle can be integrated, shared, and transformed into experience.',
   'Sobrecarga ou apego ao resultado dificultam o encerramento necessário.', 'Overload or attachment to the result make necessary closure difficult.'),
  (11, 'page', 12, 'Valete', 'Page',
   'a jovem figura observa e aprende a manejar o emblema do naipe', 'the young figure observes and learns to handle the suit’s emblem',
   'a notícia, o estudo e a curiosidade que abrem uma experiência', 'news, study, and curiosity opening an experience',
   'Curiosidade e disposição para aprender renovam a relação com o tema.', 'Curiosity and willingness to learn renew the relationship with the theme.',
   'Imaturidade, mensagem incompleta ou entusiasmo sem preparo pedem verificação.', 'Immaturity, an incomplete message, or unprepared enthusiasm call for verification.'),
  (12, 'knight', 11, 'Cavaleiro', 'Knight',
   'o cavaleiro coloca o emblema do naipe em deslocamento', 'the knight sets the suit’s emblem in motion',
   'a busca, a missão e a força que persegue uma direção', 'a quest, mission, and force pursuing a direction',
   'Compromisso e movimento fazem a energia atravessar novas fronteiras.', 'Commitment and movement carry the energy across new boundaries.',
   'Pressa, insistência ou conquista sem escuta podem desorganizar o caminho.', 'Haste, insistence, or conquest without listening may disrupt the path.'),
  (13, 'queen', 13, 'Rainha', 'Queen',
   'a rainha recebe e governa internamente o emblema do naipe', 'the queen receives and inwardly governs the suit’s emblem',
   'a maturidade receptiva, a profundidade e a autoridade interior', 'receptive maturity, depth, and inner authority',
   'Presença e domínio interior permitem nutrir o tema com profundidade.', 'Presence and inner mastery make it possible to nurture the theme deeply.',
   'Controle indireto, absorção excessiva ou fechamento drenam a capacidade de troca.', 'Indirect control, over-absorption, or withdrawal drain the capacity to exchange.'),
  (14, 'king', 14, 'Rei', 'King',
   'o rei assume responsabilidade externa pelo emblema do naipe', 'the king assumes outward responsibility for the suit’s emblem',
   'a experiência, a decisão e a autoridade que organiza o mundo', 'experience, decision, and authority organizing the world',
   'Experiência e responsabilidade oferecem direção estável ao que precisa avançar.', 'Experience and responsibility offer stable direction to what must move forward.',
   'Autoridade rígida, posse ou necessidade de controle abafam outras perspectivas.', 'Rigid authority, possessiveness, or the need for control silence other perspectives.')
)
select
  'marseille-' || ranks.id_rank || '-of-' || suits.suit,
  'marseille',
  ranks.card_number,
  suits.suit,
  suits.file_prefix || lpad(ranks.file_number::text, 2, '0') || '.png',
  ranks.name_pt_br || ' de ' || suits.name_pt_br,
  ranks.name_en || ' of ' || suits.name_en,
  'No Marselha, ' || ranks.visual_pt_br || '. Sem uma cena narrativa imposta, a composição aproxima ' || ranks.stage_pt_br || ' de ' || suits.domain_pt_br || '.',
  'In the Marseille deck, ' || ranks.visual_en || '. Without an imposed narrative scene, the composition joins ' || ranks.stage_en || ' with ' || suits.domain_en || '.',
  ranks.light_pt_br || ' ' || suits.light_pt_br,
  ranks.light_en || ' ' || suits.light_en,
  ranks.shadow_pt_br || ' ' || suits.shadow_pt_br,
  ranks.shadow_en || ' ' || suits.shadow_en
from suits cross join ranks;
