--liquibase formatted sql

--changeset arkana:20260817-09-seed-zen-deck
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(*) from public.decks where id = 'zen'
insert into public.decks (id, display_order, name_pt_br, name_en, card_count, active)
values ('zen', 3, 'Baralho Zen', 'Zen Deck', 79, true);

--changeset arkana:20260817-10-seed-zen-major-cards
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(*) from public.tarot_cards where deck_id = 'zen' and suit = 'major'
insert into public.tarot_cards (
  id, deck_id, card_number, suit, image_path,
  name_pt_br, name_en, description_pt_br, description_en,
  light_pt_br, light_en, shadow_pt_br, shadow_en
)
values
  ('zen-openness', 'zen', 0, 'major', 'Major00.png', 'Abertura', 'Openness', 'Um horizonte sem marcas convida a começar antes que todas as respostas estejam prontas.', 'An unmarked horizon invites a beginning before every answer is ready.', 'Curiosidade e confiança devolvem movimento ao que estava parado.', 'Curiosity and trust restore movement to what had become still.', 'Ingenuidade ou fuga das consequências pode disfarçar-se de liberdade.', 'Naivety or avoidance of consequences may disguise itself as freedom.'),
  ('zen-presence', 'zen', 1, 'major', 'Major01.png', 'Presença', 'Presence', 'A atenção reúne corpo, respiração e ambiente num único instante habitável.', 'Attention gathers body, breath, and surroundings into one inhabitable moment.', 'Foco sereno permite agir com precisão e inteireza.', 'Calm focus makes precise and wholehearted action possible.', 'Controle excessivo transforma atenção em vigilância e tensão.', 'Excessive control turns attention into vigilance and tension.'),
  ('zen-inner-listening', 'zen', 2, 'major', 'Major02.png', 'Escuta Interior', 'Inner Listening', 'O ruído externo diminui para que uma percepção sutil encontre linguagem.', 'Outer noise recedes so a subtle perception can find language.', 'Receptividade e discernimento revelam o que já era conhecido por dentro.', 'Receptivity and discernment reveal what was already known within.', 'Isolamento ou fantasia podem ser confundidos com intuição.', 'Isolation or fantasy may be mistaken for intuition.'),
  ('zen-creation', 'zen', 3, 'major', 'Major03.png', 'Criação', 'Creation', 'Formas ainda invisíveis encontram matéria quando desejo e cuidado trabalham juntos.', 'Forms not yet visible find matter when desire and care work together.', 'Expressão fértil transforma possibilidade em algo compartilhável.', 'Fertile expression turns possibility into something that can be shared.', 'Excesso de produção pode encobrir vazio, dispersão ou necessidade de aprovação.', 'Overproduction may conceal emptiness, scattering, or a need for approval.'),
  ('zen-autonomy', 'zen', 4, 'major', 'Major04.png', 'Autonomia', 'Autonomy', 'Uma presença firme escolhe seu eixo sem precisar dominar o espaço ao redor.', 'A steady presence chooses its axis without needing to dominate the surrounding space.', 'Limites conscientes sustentam liberdade e responsabilidade.', 'Conscious boundaries support freedom and responsibility.', 'Rigidez e oposição automática podem parecer independência.', 'Rigidity and automatic opposition may look like independence.'),
  ('zen-fertile-emptiness', 'zen', 5, 'major', 'Major05.png', 'Vazio Fértil', 'Fertile Emptiness', 'O intervalo sem forma guarda condições para um nascimento ainda sem nome.', 'The formless interval holds conditions for a birth not yet named.', 'Pausa e disponibilidade abrem espaço para o essencial emergir.', 'Pause and availability make room for what is essential to emerge.', 'Apatia ou desistência podem ser romantizadas como desapego.', 'Apathy or resignation may be romanticized as detachment.'),
  ('zen-encounter', 'zen', 6, 'major', 'Major06.png', 'Encontro', 'Encounter', 'Duas presenças aproximam-se sem abandonar a própria integridade.', 'Two presences draw near without abandoning their own integrity.', 'Reciprocidade permite vínculo, escolha e transformação mútua.', 'Reciprocity allows connection, choice, and mutual transformation.', 'Fusão, dependência ou projeção podem ocupar o lugar do encontro real.', 'Fusion, dependency, or projection may replace genuine encounter.'),
  ('zen-clarity', 'zen', 7, 'major', 'Major07.png', 'Clareza', 'Clarity', 'Camadas de névoa se separam até que direção e limite possam ser vistos.', 'Layers of mist separate until direction and boundary can be seen.', 'Compreensão limpa organiza prioridades e orienta a ação.', 'Clear understanding organizes priorities and guides action.', 'Certeza prematura pode eliminar nuances importantes.', 'Premature certainty may erase important nuances.'),
  ('zen-courage', 'zen', 8, 'major', 'Major08.png', 'Coragem', 'Courage', 'O caminho se forma sob o passo de quem aceita avançar sem garantias.', 'The path forms beneath the step of one willing to move without guarantees.', 'Vulnerabilidade consciente converte medo em presença ativa.', 'Conscious vulnerability turns fear into active presence.', 'Impulsividade ou dureza podem representar uma coragem apenas aparente.', 'Impulsiveness or hardness may perform a courage that is only apparent.'),
  ('zen-solitude', 'zen', 9, 'major', 'Major09.png', 'Solitude', 'Solitude', 'A distância voluntária devolve contorno à própria voz.', 'Chosen distance restores definition to one''s own voice.', 'Recolhimento oferece autonomia, descanso e escuta profunda.', 'Withdrawal offers autonomy, rest, and deep listening.', 'Fechamento defensivo pode transformar solitude em isolamento.', 'Defensive withdrawal may turn solitude into isolation.'),
  ('zen-flow', 'zen', 10, 'major', 'Major10.png', 'Fluxo', 'Flow', 'A mudança contínua revela que estabilidade também pode existir em movimento.', 'Continuous change reveals that stability can also exist within movement.', 'Flexibilidade permite responder ao momento sem perder o centro.', 'Flexibility allows a response to the moment without losing the center.', 'Passividade e falta de direção podem ser justificadas como entrega.', 'Passivity and lack of direction may be justified as surrender.'),
  ('zen-crossing', 'zen', 11, 'major', 'Major11.png', 'Travessia', 'Crossing', 'Entre uma margem conhecida e outra ainda distante, cada passo redefine a jornada.', 'Between a known shore and one still distant, each step redefines the journey.', 'Persistência e adaptação tornam possível atravessar uma transição.', 'Persistence and adaptation make it possible to cross a transition.', 'Pressa por chegar pode impedir a aprendizagem oferecida pelo percurso.', 'Hurry to arrive may prevent the learning offered by the passage.'),
  ('zen-new-perspective', 'zen', 12, 'major', 'Major12.png', 'Novo Olhar', 'New Perspective', 'Uma suspensão deliberada muda a relação entre figura, fundo e significado.', 'A deliberate suspension changes the relationship between figure, ground, and meaning.', 'Reenquadrar a experiência revela alternativas antes invisíveis.', 'Reframing experience reveals alternatives that were previously invisible.', 'Adiar indefinidamente uma escolha pode se esconder atrás da contemplação.', 'Indefinitely delaying a choice may hide behind contemplation.'),
  ('zen-transformation', 'zen', 13, 'major', 'Major13.png', 'Transformação', 'Transformation', 'Uma forma se desfaz para que seus elementos participem de outra organização.', 'One form dissolves so its elements can participate in another arrangement.', 'Desapego e elaboração liberam energia para uma mudança verdadeira.', 'Release and integration free energy for genuine change.', 'Destruição sem cuidado ou apego ao que terminou prolongam a passagem.', 'Careless destruction or attachment to what has ended prolong the passage.'),
  ('zen-integration', 'zen', 14, 'major', 'Major14.png', 'Integração', 'Integration', 'Diferenças permanecem visíveis enquanto aprendem a compor um sistema vivo.', 'Differences remain visible while learning to compose a living system.', 'Síntese e diálogo reconciliam partes sem apagar sua singularidade.', 'Synthesis and dialogue reconcile parts without erasing their uniqueness.', 'Harmonia forçada pode silenciar conflitos que ainda pedem elaboração.', 'Forced harmony may silence conflicts that still need to be worked through.'),
  ('zen-conditioning', 'zen', 15, 'major', 'Major15.png', 'Condicionamento', 'Conditioning', 'Padrões herdados repetem-se até que sejam vistos como escolhas possíveis, não destinos.', 'Inherited patterns repeat until they are seen as possible choices rather than destiny.', 'Reconhecer influências devolve liberdade para escolher conscientemente.', 'Recognizing influences restores the freedom to choose consciously.', 'Culpar o passado pode evitar a responsabilidade pelo passo presente.', 'Blaming the past may avoid responsibility for the present step.'),
  ('zen-awakening', 'zen', 16, 'major', 'Major16.png', 'Despertar', 'Awakening', 'Uma ruptura de luz atravessa estruturas que pareciam definitivas.', 'A rupture of light crosses structures that once seemed final.', 'Verdade súbita dissolve automatismos e inicia reorganização.', 'Sudden truth dissolves automatic patterns and begins reorganization.', 'Choque sem integração pode gerar desorientação ou nova rigidez.', 'Shock without integration may create disorientation or new rigidity.'),
  ('zen-silence', 'zen', 17, 'major', 'Major17.png', 'Silêncio', 'Silence', 'Quando as ondas cessam, a experiência pode ser percebida sem comentário imediato.', 'When the waves settle, experience can be perceived without immediate commentary.', 'Quietude restaura espaço interno e precisão de escuta.', 'Stillness restores inner space and precision of listening.', 'Supressão, distância emocional ou medo de falar podem imitar silêncio.', 'Suppression, emotional distance, or fear of speaking may imitate silence.'),
  ('zen-memory', 'zen', 18, 'major', 'Major18.png', 'Memória', 'Memory', 'Fragmentos do vivido retornam como imagens que pedem contexto e cuidado.', 'Fragments of lived experience return as images asking for context and care.', 'Lembrar com presença transforma experiência em compreensão.', 'Remembering with presence transforms experience into understanding.', 'Nostalgia ou ruminação podem aprisionar o presente numa narrativa antiga.', 'Nostalgia or rumination may imprison the present in an old narrative.'),
  ('zen-innocence', 'zen', 19, 'major', 'Major19.png', 'Inocência', 'Innocence', 'Um olhar disponível encontra novidade até no que já foi visto muitas vezes.', 'An available gaze finds newness even in what has been seen many times.', 'Simplicidade e encantamento renovam relação com a vida.', 'Simplicity and wonder renew one''s relationship with life.', 'Negar complexidade ou responsabilidade não é o mesmo que permanecer aberto.', 'Denying complexity or responsibility is not the same as remaining open.'),
  ('zen-beyond-appearances', 'zen', 20, 'major', 'Major20.png', 'Além das Aparências', 'Beyond Appearances', 'A superfície torna-se translúcida e revela relações que antes pareciam separadas.', 'The surface becomes translucent and reveals relationships that once seemed separate.', 'Discernimento atravessa projeções e reconhece padrões profundos.', 'Discernment moves through projections and recognizes deeper patterns.', 'Desconfiar de tudo pode virar outra aparência de lucidez.', 'Distrusting everything may become another appearance of insight.'),
  ('zen-wholeness', 'zen', 21, 'major', 'Major21.png', 'Completude', 'Wholeness', 'Partes diversas encontram proporção suficiente para sustentar um todo aberto.', 'Diverse parts find enough proportion to sustain an open whole.', 'Conclusão, gratidão e pertencimento permitem celebrar o percurso.', 'Completion, gratitude, and belonging make it possible to honor the journey.', 'Perfeccionismo ou medo do próximo ciclo podem impedir uma conclusão real.', 'Perfectionism or fear of the next cycle may prevent genuine completion.'),
  ('zen-witness', 'zen', 22, 'major', 'Major22.png', 'Testemunha', 'Witness', 'A consciência observa movimento, emoção e pensamento sem se reduzir a nenhum deles.', 'Awareness observes movement, emotion, and thought without being reduced to any of them.', 'Equanimidade cria liberdade entre experiência e reação.', 'Equanimity creates freedom between experience and reaction.', 'Distanciamento frio pode usar a observação para evitar participação e afeto.', 'Cold detachment may use observation to avoid participation and feeling.');

--changeset arkana:20260817-11-seed-zen-field-cards
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 select count(*) from public.tarot_cards where deck_id = 'zen' and suit <> 'major'
insert into public.tarot_cards (
  id, deck_id, card_number, suit, image_path,
  name_pt_br, name_en, description_pt_br, description_en,
  light_pt_br, light_en, shadow_pt_br, shadow_en
)
with suits (
  suit, file_prefix, name_pt_br, name_en,
  domain_pt_br, domain_en, light_pt_br, light_en, shadow_pt_br, shadow_en
) as (values
  ('cups', 'Cups', 'Água', 'Water', 'sensibilidade, vínculo, intuição e circulação emocional', 'sensitivity, connection, intuition, and emotional circulation', 'Escuta afetiva deixa a experiência mover-se sem perder contorno.', 'Emotional listening lets experience move without losing its shape.', 'Fusão, idealização ou emoção represada podem turvar a relação.', 'Fusion, idealization, or blocked emotion may cloud the relationship.'),
  ('pentacles', 'Pentacles', 'Terra', 'Earth', 'corpo, recursos, ritmo e sustentação concreta', 'body, resources, rhythm, and concrete support', 'Presença prática transforma intenção em cuidado sustentável.', 'Practical presence turns intention into sustainable care.', 'Apego, inércia ou excesso de controle podem endurecer o que pede cultivo.', 'Attachment, inertia, or excessive control may harden what needs cultivation.'),
  ('swords', 'Swords', 'Ar', 'Air', 'pensamento, linguagem, discernimento e perspectiva', 'thought, language, discernment, and perspective', 'Clareza mental distingue fatos, histórias e escolhas.', 'Mental clarity distinguishes facts, stories, and choices.', 'Ruminação, julgamento ou abstração excessiva podem cortar o vínculo com a experiência.', 'Rumination, judgment, or excessive abstraction may sever contact with experience.'),
  ('wands', 'Wands', 'Fogo', 'Fire', 'vitalidade, desejo, iniciativa e expressão criadora', 'vitality, desire, initiative, and creative expression', 'Energia consciente encontra direção e aquece o que precisa nascer.', 'Conscious energy finds direction and warms what needs to be born.', 'Impulsividade, disputa ou esgotamento podem consumir a própria fonte.', 'Impulsiveness, rivalry, or exhaustion may consume the source itself.')
), ranks (
  card_number, id_rank, name_pt_br, name_en,
  stage_pt_br, stage_en, light_pt_br, light_en, shadow_pt_br, shadow_en
) as (values
  (1, 'seed', 'Semente', 'Seed', 'o instante em que uma potência ainda indivisa pede começo', 'the moment when undivided potential asks to begin', 'Uma possibilidade essencial encontra permissão para existir.', 'An essential possibility receives permission to exist.', 'Esperar certeza total mantém a semente fora do tempo.', 'Waiting for total certainty keeps the seed outside its season.'),
  (2, 'mirror', 'Espelho', 'Mirror', 'a polaridade que revela semelhanças, diferenças e escolha', 'the polarity that reveals similarities, differences, and choice', 'Duas forças podem reconhecer-se e encontrar relação.', 'Two forces can recognize one another and find relationship.', 'Comparação rígida ou indecisão prolongada divide o que poderia dialogar.', 'Rigid comparison or prolonged indecision divides what could enter dialogue.'),
  (3, 'bloom', 'Florescimento', 'Bloom', 'a expansão que nasce do encontro e busca expressão', 'the expansion born from encounter and seeking expression', 'Crescimento compartilhado dá forma ao que estava começando.', 'Shared growth gives form to what was beginning.', 'Expansão sem centro pode dispersar recursos e atenção.', 'Expansion without a center may scatter resources and attention.'),
  (4, 'foundation', 'Fundamento', 'Foundation', 'a estrutura que protege continuidade, limite e repouso', 'the structure that protects continuity, boundary, and rest', 'Uma base clara permite permanecer e aprofundar.', 'A clear foundation makes it possible to remain and deepen.', 'Segurança pode endurecer em repetição ou fechamento.', 'Safety may harden into repetition or closure.'),
  (5, 'friction', 'Fricção', 'Friction', 'o desequilíbrio que expõe tensões e exige reorganização', 'the imbalance that exposes tensions and demands reorganization', 'O desconforto mostra onde mudança e aprendizagem são necessárias.', 'Discomfort shows where change and learning are needed.', 'Conflito sem escuta pode tornar-se desgaste repetido.', 'Conflict without listening may become repeated exhaustion.'),
  (6, 'accord', 'Acordo', 'Accord', 'a recomposição que permite troca depois da tensão', 'the recomposition that allows exchange after tension', 'Ajustes conscientes restauram proporção e reciprocidade.', 'Conscious adjustments restore proportion and reciprocity.', 'Harmonia aparente pode esconder concessões que não se sustentam.', 'Apparent harmony may hide concessions that cannot be sustained.'),
  (7, 'trial', 'Prova', 'Trial', 'o momento de sustentar uma escolha diante de resistência', 'the moment of sustaining a choice in the face of resistance', 'Convicção flexível protege o que merece continuidade.', 'Flexible conviction protects what deserves continuity.', 'Defensividade pode transformar todo encontro em ameaça.', 'Defensiveness may turn every encounter into a threat.'),
  (8, 'passage', 'Passagem', 'Passage', 'a aceleração que transporta energia entre duas condições', 'the acceleration that carries energy between two conditions', 'Movimento coordenado destrava o que estava suspenso.', 'Coordinated movement releases what was suspended.', 'Pressa e excesso de estímulo podem eliminar direção.', 'Hurry and overstimulation may erase direction.'),
  (9, 'ripening', 'Maturação', 'Ripening', 'a consolidação que pede paciência antes da conclusão', 'the consolidation that asks for patience before completion', 'Experiência acumulada oferece resistência e refinamento.', 'Accumulated experience offers resilience and refinement.', 'Cansaço ou desconfiança podem impedir receber o que amadureceu.', 'Fatigue or distrust may prevent receiving what has ripened.'),
  (10, 'fullness', 'Plenitude', 'Fullness', 'a abundância que revela consequência, limite e partilha', 'the abundance that reveals consequence, limit, and sharing', 'O ciclo entrega frutos que podem sustentar outras pessoas.', 'The cycle yields fruits that can sustain others.', 'Acúmulo e sobrecarga podem confundir quantidade com realização.', 'Accumulation and overload may confuse quantity with fulfillment.'),
  (11, 'student', 'Aprendiz', 'Student', 'a curiosidade que toca o campo com atenção renovada', 'the curiosity that approaches the field with renewed attention', 'Disponibilidade para aprender abre uma etapa inesperada.', 'Willingness to learn opens an unexpected stage.', 'Inconstância ou fascínio pela novidade podem evitar profundidade.', 'Inconstancy or fascination with novelty may avoid depth.'),
  (12, 'traveler', 'Viajante', 'Traveler', 'o compromisso de levar experiência para além do lugar conhecido', 'the commitment to carry experience beyond the familiar place', 'Coragem em movimento transforma intenção em percurso.', 'Courage in motion turns intention into a journey.', 'Agitação ou busca compulsiva podem impedir enraizamento.', 'Restlessness or compulsive seeking may prevent rootedness.'),
  (13, 'keeper', 'Guardiã', 'Keeper', 'a capacidade de acolher, regular e fazer amadurecer', 'the capacity to receive, regulate, and bring to maturity', 'Cuidado soberano protege sem aprisionar.', 'Sovereign care protects without imprisoning.', 'Proteção excessiva pode converter cuidado em controle.', 'Excessive protection may turn care into control.'),
  (14, 'steward', 'Regente', 'Steward', 'a autoridade que orienta o campo a serviço de sua vitalidade', 'the authority that guides the field in service of its vitality', 'Domínio responsável organiza recursos sem apagar diferenças.', 'Responsible mastery organizes resources without erasing differences.', 'Poder desconectado da escuta pode dominar o que deveria servir.', 'Power disconnected from listening may dominate what it should serve.')
)
select
  'zen-' || ranks.id_rank || '-of-' || suits.suit,
  'zen',
  ranks.card_number,
  suits.suit,
  suits.file_prefix || lpad(ranks.card_number::text, 2, '0') || '.png',
  ranks.name_pt_br || case
    when suits.suit in ('cups', 'pentacles') then ' da '
    else ' do '
  end || suits.name_pt_br,
  ranks.name_en || ' of ' || suits.name_en,
  'No campo ' || case
    when suits.suit in ('cups', 'pentacles') then 'da '
    else 'do '
  end || lower(suits.name_pt_br) || ' — ' || suits.domain_pt_br || ' —, ' ||
    lower(ranks.name_pt_br) || ' representa ' || ranks.stage_pt_br || '.',
  'Within the field of ' || lower(suits.name_en) || ' — ' || suits.domain_en || ' —, ' ||
    lower(ranks.name_en) || ' represents ' || ranks.stage_en || '.',
  ranks.light_pt_br || ' ' || suits.light_pt_br,
  ranks.light_en || ' ' || suits.light_en,
  ranks.shadow_pt_br || ' ' || suits.shadow_pt_br,
  ranks.shadow_en || ' ' || suits.shadow_en
from suits
cross join ranks;
